variables:
    ascName: OryxMCR
    acrName: oryxdevmcr.azurecr.io
    skipComponentGovernanceDetection: true
  
jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build DotNetCore runtime base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: dotnetcore
    artifactsFileName: dotnetcore-runtimeimage-bases.txt
    jobName: Build_DotNetCore_BaseImage

- job: Release_DotNetCoreRuntimeBaseImage
  dependsOn: Build_DotNetCore_BaseImage
  displayName: Push images to MCR
  timeoutInMinutes: 250
  pool:
    name: OryxLinux
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'dotnetcore'
