resources:
- repo: self

variables:
- group: Oryx

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
    - job: Job_SignBinaries
      displayName: Sign Detector Binaries and NuGet packages
      pool:
        name: VSEng-MicroBuildVS2017
        demands:
        - msbuild
        - visualstudio
      variables:
        SignType: 'test'
        skipComponentGovernanceDetection: true
      steps:
      - template: templates/_signBinaryDetector.yml
    - job: Job_BuildAndTestDetector
      displayName: Build and test detector
      pool:
        name: OryxLinux
      steps:
      - template: templates/_buildTemplateDetector.yml

  - stage: Release
    displayName: Release Stage
    dependsOn: Build
    condition: >
      and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),
      startsWith(variables['Build.SourceBranch'],'refs/heads/kichalla/' )))
    jobs:
    - job: Release_GitHub
      displayName: Create GitHub release
      pool:
        name: OryxLinux
      variables:
        skipComponentGovernanceDetection: true
    
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download artifacts to publish to release'
        inputs:
          artifactName: 'Detector'
          path: $(Build.SourcesDirectory)/artifacts
    
      - task: GitHubRelease@0
        displayName: 'GitHub release (create)'
        inputs:
          gitHubConnection: 'Oryx-GitHub'
          repositoryName: Microsoft/Oryx
          tagSource: manual
          tag: '$(RELEASE_TAG_NAME)'
          assets: $(Build.SourcesDirectory)/artifacts/Detector/*.nupkg

trigger: none