resources:
- repo: self
  fetchDepth: 15

variables:
- group: Oryx

jobs:
- job: Job_Security
  displayName: Security
  pool:
    name: Hosted VS2017
  steps:
  - template: templates/_securityChecks.yml

- job: Job_BuildImage
  displayName: Build and Test Build Images
  pool:
    name: OryxLinux
  timeoutInMinutes: 300
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
      echo "##vso[task.setvariable variable=TestBuildImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml

- job: Job_Stretch_RuntimeImages
  displayName: Build and Test Stretch Runtime Images
  pool:
    name: OryxLinux
  timeoutInMinutes: 300
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml

- job: Job_Buster_RuntimeImages
  displayName: Build and Test Buster Runtime Images
  pool:
    name: OryxLinux
  timeoutInMinutes: 300
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml

trigger: none
